# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [9]:
import pandas as pd

from sklearn.ensemble import RandomForestRegressor as RFR    

from sklearn.model_selection import train_test_split as tts 

## Regression Model Evaluation

In [20]:
from sklearn.datasets import load_boston

data = load_boston()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=['MEDV'])

data_1 = pd.concat([X, y], axis=1)

/Users/ronaldhernandez/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the Califo

In [19]:
data

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [30]:
data_1.shape

(506, 14)

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [29]:
X_train, X_test, y_train, y_test = tts(data['data'], data['target'], test_size=0.2)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((404, 13), (102, 13), (404,), (102,))

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [42]:
rf=RFR()   

rf.fit(X_train, y_train)   

y_pred_train = rf.predict(X_train) 

y_pred_test = rf.predict(X_test) 

y_pred_test

array([21.172, 21.486, 33.281, 22.819, 40.31 , 30.244, 20.664, 11.656,
       24.654, 34.069, 35.928, 20.275, 13.471, 15.287, 20.539, 33.083,
       33.865, 22.128, 25.017, 23.386, 32.348, 22.572,  9.579, 21.128,
       15.615, 40.365, 20.757, 19.579, 19.286, 27.633, 21.916, 19.787,
       27.   , 20.116, 11.788, 10.25 , 19.88 , 17.585, 15.186, 22.296,
       12.743, 33.799, 23.164, 29.846, 24.733, 19.262, 19.132, 20.606,
       10.7  , 19.691, 16.205, 14.437, 33.094, 15.225, 13.622, 11.813,
       20.387, 20.041, 24.764, 23.554, 28.364, 29.047, 17.251, 21.656,
       28.857, 27.017, 23.22 , 15.361, 42.292, 33.69 , 26.038, 23.351,
       11.292, 22.35 , 15.472, 26.096, 42.824, 22.067, 20.839, 17.85 ,
       25.88 , 46.071, 18.097, 25.61 , 20.004, 14.896, 21.952, 15.762,
       26.721, 32.656, 15.869, 13.828, 46.614, 14.43 , 21.432, 22.183,
       19.259, 19.914, 12.362, 24.392,  7.377, 21.077])

In [43]:
y_pred_test.shape,  y_test.shape

((102,), (102,))

## 3. Calculate and print R-squared for both the training and the testing set.

In [44]:
from sklearn.metrics import r2_score as r2

r2(y_train, y_pred_train)


0.9806980155476422

In [45]:
r2(y_test, y_pred_test)

0.8498501452823559

## 4. Calculate and print mean squared error for both the training and the testing set.

In [47]:
from sklearn.metrics import mean_squared_error as mse

mse(y_train, y_pred_train)

1.5833708861386129

In [48]:
mse(y_test, y_pred_test)

14.076272941176457

## 5. Calculate and print mean absolute error for both the training and the testing set.

In [36]:
from sklearn.metrics import mean_absolute_error as mae  

mae(y_test, y_pred)

2.6599999999999993

## Classification Model Evaluation

In [49]:
from sklearn.datasets import load_iris

data = load_iris()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=["class"])

data_2 = pd.concat([X, y], axis=1)

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [50]:
X_train, X_test, y_train, y_test = tts(data['data'], data['target'], test_size=0.2)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((120, 4), (30, 4), (120,), (30,))

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [54]:
from sklearn.linear_model import LogisticRegression as LogReg

logreg=LogReg()

logreg.fit(X_train, y_train)

y_pred_train = logreg.predict(X_train) 

y_pred_test = logreg.predict(X_test) 

y_pred_test[:5]

/Users/ronaldhernandez/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([1, 0, 2, 2, 1])

In [55]:
y_pred_train[:5]

array([2, 0, 1, 1, 1])

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [56]:
from sklearn.metrics import accuracy_score as acc

acc(y_test, y_pred_test)

1.0

In [57]:
acc(y_train, y_pred_train)

0.9666666666666667

## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [74]:
from sklearn.metrics import balanced_accuracy_score as bas

bas(y_test, y_pred_test)

1.0

In [75]:
bas(y_train, y_pred_train)

0.9672764227642277

## 10. Calculate and print the precision score for both the training and the testing set.

In [78]:
from sklearn.metrics import precision_score as prec

prec(y_test, y_pred_test, average=None)

array([1., 1., 1.])

In [64]:
prec(y_train, y_pred_train, average=None)

array([1.        , 0.97435897, 0.92857143])

## 11. Calculate and print the recall score for both the training and the testing set.

In [66]:
from sklearn.metrics import recall_score as rec

rec(y_test, y_pred_test, average=None)

array([1., 1., 1.])

In [67]:
rec(y_train, y_pred_train, average=None)

array([1.        , 0.92682927, 0.975     ])

## 12. Calculate and print the F1 score for both the training and the testing set.

In [69]:
from sklearn.metrics import f1_score as f1

f1(y_test, y_pred_test, average=None)

array([1., 1., 1.])

In [70]:
f1(y_train, y_pred_train, average=None)

array([1.        , 0.95      , 0.95121951])

## 13. Generate confusion matrices for both the training and the testing set.

In [71]:
from sklearn.metrics import confusion_matrix as cm

cm(y_test, y_pred_test)

array([[11,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 10]])

In [72]:
cm(y_train, y_pred_train)

array([[39,  0,  0],
       [ 0, 38,  3],
       [ 0,  1, 39]])

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.